module
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.Cosets
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.DiscriminantPairing
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.DiscriminantNondegenerate
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.IsotropicBound
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.DualLatticeFinite
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.DualCovolume
import Mathlib.Algebra.Module.ZLattice.Covolume
import Mathlib.Analysis.Fourier.FiniteAbelian.PontryaginDuality
import Mathlib.Algebra.Module.Submodule.Ker
import Mathlib.Algebra.Module.Submodule.Range
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.LinearAlgebra.Quotient.Basic

/-!
# Overlattices from discriminant subgroups

From a subgroup `H ≤ L*/L`, one can form an overlattice `L_H` defined as the preimage of `H`
inside `L*`. Its index in `L` is `|H|`, and covolumes satisfy
`covolume(L_H) = covolume(L) / |H|`.

This is standard lattice theory used implicitly in Cohn-Elkies uniqueness arguments. In
dimension `24`, we apply this construction to the subgroup generated by center orbit cosets.

## Main definitions
* `preimageSubmodule`
* `centersSubgroup`
* `centersOverlattice`
-/


namespace SpherePacking.Dim24.Uniqueness.RigidityClassify

open scoped Pointwise RealInnerProductSpace
open MeasureTheory

noncomputable section

local notation "ℝ²⁴" => EuclideanSpace ℝ (Fin 24)

/-- The preimage of a submodule `H ≤ L*/L` inside the dual lattice `L*`. -/
@[expose]
public def preimageSubmodule (L : Submodule ℤ ℝ²⁴) (H : Submodule ℤ (DiscriminantGroup L)) :
    Submodule ℤ (DualLattice L) :=
  Submodule.comap (Submodule.mkQ (latticeInDual L)) H

/-- The embedded lattice `L` lies in the preimage overlattice for any subgroup `H`. -/
@[simp]
public lemma latticeInDual_le_preimageSubmodule (L : Submodule ℤ ℝ²⁴)
    (H : Submodule ℤ (DiscriminantGroup L)) :
    latticeInDual L ≤ preimageSubmodule L H := by
  -- `p ≤ comap (mkQ p) _` for any submodule of the quotient.
  simpa [preimageSubmodule] using (Submodule.le_comap_mkQ (p := latticeInDual L) H)

/-- Mapping `preimageSubmodule L H` to `L*/L` recovers `H`. -/
@[simp]
public lemma map_mkQ_preimageSubmodule (L : Submodule ℤ ℝ²⁴)
    (H : Submodule ℤ (DiscriminantGroup L)) :
    Submodule.map (Submodule.mkQ (latticeInDual L)) (preimageSubmodule L H) = H := by
  -- `map f (comap f H) = H ⊓ range f`, and `range (mkQ p) = ⊤`.
  simpa [preimageSubmodule, Submodule.range_mkQ] using
    (Submodule.map_comap_eq (f := Submodule.mkQ (latticeInDual L)) H)

/-! ### The candidate subgroup coming from `S.centers`

We can always form the `ℤ`-submodule generated by the image of `orbitCoset`.

The main missing rigidity input is to show this generated submodule has cardinality `S.numReps`,
and that the resulting preimage in the dual lattice acts transitively on centers.-/

/-- The submodule of the discriminant group generated by the center orbit cosets. -/
@[expose]
public noncomputable def centersSubgroup (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers) : Submodule ℤ (DiscriminantGroup S.lattice) :=
  Submodule.span ℤ (Set.range (orbitCoset (S := S) hSpec hDens x0))

/-- The orbit-coset map, viewed as a map into the generated subgroup. -/
@[expose]
public noncomputable def orbitToCentersSubgroup (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers) :
    Quotient S.addAction.orbitRel → centersSubgroup (S := S) hSpec hDens x0 :=
  fun q => ⟨orbitCoset (S := S) hSpec hDens x0 q, Submodule.subset_span ⟨q, rfl⟩⟩

/-- The map from the orbit quotient into `centersSubgroup` is injective. -/
public theorem orbitToCentersSubgroup_injective (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers) :
    Function.Injective (orbitToCentersSubgroup (S := S) hSpec hDens x0) := by
  intro q₁ q₂ hq
  apply orbitCoset_injective (S := S) (hSpec := hSpec) (hDens := hDens) (x0 := x0)
  exact congrArg Subtype.val hq

/-- The corresponding overlattice inside `S.lattice*`, viewed as a submodule of `ℝ²⁴`. -/
@[expose]
public noncomputable def centersOverlattice (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers) : Submodule ℤ ℝ²⁴ :=
  (preimageSubmodule S.lattice (centersSubgroup (S := S) hSpec hDens x0)).map
    (Submodule.subtype (DualLattice S.lattice))

/-- If `orbitToCentersSubgroup` is surjective, then `x0 + centersOverlattice ⊆ S.centers`. -/
public theorem vadd_centersOverlattice_subset_centers_of_surjective (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers)
    (hsurj : Function.Surjective (orbitToCentersSubgroup (S := S) hSpec hDens x0)) :
    (x0 : ℝ²⁴) +ᵥ (centersOverlattice (S := S) hSpec hDens x0 : Set ℝ²⁴) ⊆
      (S.centers : Set ℝ²⁴) := by
  intro y hy
  rcases hy with ⟨v, hv, rfl⟩
  rcases hv with ⟨p, hp, rfl⟩
  -- `p` lives in the dual lattice and maps to an element of the centers subgroup.
  have hpH :
      (Submodule.Quotient.mk p :
          DiscriminantGroup S.lattice) ∈
        centersSubgroup (S := S) hSpec hDens x0 := by
    simpa [preimageSubmodule] using hp
  let h : centersSubgroup (S := S) hSpec hDens x0 :=
    ⟨Submodule.Quotient.mk p, hpH⟩
  rcases hsurj h with ⟨q, hq⟩
  -- pick a center representative of `q`
  let xq : S.centers := Quotient.out q
  have hcos :
      (Submodule.Quotient.mk p :
          DiscriminantGroup S.lattice) =
        orbitCoset (S := S) hSpec hDens x0 q := by
    -- `hq : orbitToCentersSubgroup q = h`, so comparing values gives `orbitCoset q = mk p`.
    simpa [orbitToCentersSubgroup] using (congrArg Subtype.val hq).symm
  have horbit_mk :
      orbitCoset (S := S) hSpec hDens x0 q =
        centerCoset (S := S) hSpec hDens x0 xq := by
    have hxq : Quotient.mk'' xq = q := by
      simp [xq]
    rw [← hxq]
    simp [orbitCoset]
  have hmk_eq :
      (Submodule.Quotient.mk p :
          DiscriminantGroup S.lattice) =
        (Submodule.Quotient.mk (centerDiffDual (S := S) hSpec hDens x0 xq) :
          DiscriminantGroup S.lattice) := by
    simpa [centerCoset] using (hcos.trans horbit_mk)
  have hmemLat :
      (p - centerDiffDual (S := S) hSpec hDens x0 xq : DualLattice S.lattice) ∈
        latticeInDual S.lattice :=
    (mk_eq_mk_iff_sub_mem (L := S.lattice) p (centerDiffDual (S := S) hSpec hDens x0 xq)).1
      (by simpa using hmk_eq)
  have hlatt :
      ((p : ℝ²⁴) - ((xq : ℝ²⁴) - (x0 : ℝ²⁴))) ∈ S.lattice := by
    assumption
  -- Translate the chosen center by the lattice element `p - (xq - x0)`.
  have ht_centers :
      ((p : ℝ²⁴) - ((xq : ℝ²⁴) - (x0 : ℝ²⁴))) + (xq : ℝ²⁴) ∈ (S.centers : Set ℝ²⁴) :=
    S.lattice_action hlatt xq.property
  simpa [sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using ht_centers

/-- If `L ≤ L*`, then `S.lattice` is contained in `centersOverlattice`. -/
public lemma lattice_le_centersOverlattice_of_lattice_le_dual (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers)
    (hLdual : S.lattice ≤ DualLattice S.lattice) :
    S.lattice ≤ centersOverlattice (S := S) hSpec hDens x0 := by
  intro v hv
  have hvDual : (v : ℝ²⁴) ∈ DualLattice S.lattice := hLdual hv
  refine ⟨(⟨v, hvDual⟩ : DualLattice S.lattice), ?_, rfl⟩
  -- element lies in the preimage submodule because it lies in `latticeInDual`
  change (⟨v, hvDual⟩ : DualLattice S.lattice) ∈ preimageSubmodule S.lattice
      (centersSubgroup (S := S) hSpec hDens x0)
  have : (⟨v, hvDual⟩ : DualLattice S.lattice) ∈ latticeInDual S.lattice := by
    simpa [mem_latticeInDual_iff] using hv
  exact (latticeInDual_le_preimageSubmodule (L := S.lattice)
    (H := centersSubgroup (S := S) hSpec hDens x0)) this

/-- Every center lies in the coset `x0 + centersOverlattice`. -/
public lemma centers_subset_vadd_centersOverlattice (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers) :
    (S.centers : Set ℝ²⁴) ⊆
      (x0 : ℝ²⁴) +ᵥ (centersOverlattice (S := S) hSpec hDens x0 : Set ℝ²⁴) := by
  intro x hx
  -- package `x` as an element of `S.centers`
  let x' : S.centers := ⟨x, hx⟩
  -- the dual-lattice element `x' - x0`
  let d : DualLattice S.lattice := centerDiffDual (S := S) hSpec hDens x0 x'
  have hdH : (Submodule.Quotient.mk d : DiscriminantGroup S.lattice) ∈
      centersSubgroup (S := S) hSpec hDens x0 := by
    -- `d` is the value defining `centerCoset x'`, and `centerCoset x'` is in the span of the range.
    have : Submodule.Quotient.mk d =
        orbitCoset (S := S) hSpec hDens x0 (Quotient.mk'' x') := by
      simp [orbitCoset, centerCoset, d]
    -- now use membership in the span of the range
    refine Submodule.subset_span ?_
    refine ⟨Quotient.mk'' x', this.symm⟩
  -- By definition, `d` lies in the preimage submodule.
  have hdPre :
      d ∈ preimageSubmodule S.lattice (centersSubgroup (S := S) hSpec hDens x0) := by
    -- unfold `preimageSubmodule = comap mkQ _`
    -- and use `hdH`.
    simpa [preimageSubmodule] using hdH
  -- Convert `d ∈ preimageSubmodule` into membership in `centersOverlattice`.
  have hdOver : (d : ℝ²⁴) ∈ centersOverlattice (S := S) hSpec hDens x0 := by
    refine ⟨d, hdPre, rfl⟩
  refine ⟨(d : ℝ²⁴), hdOver, ?_⟩
  -- `x0 + (x' - x0) = x'`.
  simp [d, centerDiffDual, x', sub_eq_add_neg, add_left_comm]

end

end SpherePacking.Dim24.Uniqueness.RigidityClassify
