module
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.Overlattice.CentersIsotropic


/-!
# Index and covolume of the centers overlattice

This file records algebraic facts about the preimage overlattice associated to a subgroup
`H ≤ L*/L` and applies them to the subgroup generated by center orbit cosets.

The main output is the construction of an overlattice of covolume `1` (unimodular) whose cosets
describe `S.centers` as a single translate.

## Main statements
* `covolume_eq_one_of_covolume_eq_numReps_and_subgroup_card`
-/


namespace SpherePacking.Dim24.Uniqueness.RigidityClassify

open scoped Pointwise RealInnerProductSpace
open MeasureTheory

noncomputable section

local notation "ℝ²⁴" => EuclideanSpace ℝ (Fin 24)

/-- If `L ≤ L'` and `L` has full real span, then `L'` also has full real span. -/
public lemma isZLattice_of_le_of_isZLattice (L L' : Submodule ℤ ℝ²⁴)
    [DiscreteTopology L] [IsZLattice ℝ L] [DiscreteTopology L'] (hLL' : L ≤ L') :
    IsZLattice ℝ L' := by
  refine ⟨?_⟩
  have hspanL : Submodule.span ℝ (L : Set ℝ²⁴) = ⊤ :=
    IsZLattice.span_top (K := ℝ) (L := L)
  have hmono : Submodule.span ℝ (L : Set ℝ²⁴) ≤ Submodule.span ℝ (L' : Set ℝ²⁴) :=
    Submodule.span_mono (by
      intro v hv
      exact hLL' hv)
  exact top_le_iff.mp (by simpa [hspanL] using hmono)


/-- For a subgroup `H ≤ L*/L`, the corresponding preimage overlattice has relative index `|H|`. -/
theorem relIndex_preimageOverlattice_eq_card (L : Submodule ℤ ℝ²⁴)
    (H : Submodule ℤ (DiscriminantGroup L)) :
    L.toAddSubgroup.relIndex
        ((preimageSubmodule L H).map (Submodule.subtype (DualLattice L))).toAddSubgroup =
      Nat.card H := by
  -- Work in `DualLattice L`, and relate the index computation in `ℝ²⁴` to the quotient map
  -- `DualLattice L → L*/L`.
  let P : Submodule ℤ (DualLattice L) := preimageSubmodule L H
  let incl : DualLattice L →ₗ[ℤ] ℝ²⁴ := Submodule.subtype (DualLattice L)
  let inclAdd : DualLattice L →+ ℝ²⁴ := incl.toAddMonoidHom
  have hmap_incl :
      (P.map incl).toAddSubgroup = AddSubgroup.map inclAdd P.toAddSubgroup := by
    simpa [inclAdd] using (Submodule.map_toAddSubgroup (f := incl) (p := P))
  have hcomap_incl :
      AddSubgroup.comap inclAdd L.toAddSubgroup = (latticeInDual L).toAddSubgroup := by
    ext x
    simp [latticeInDual, inclAdd, incl]
  let mkQ : DualLattice L →ₗ[ℤ] DiscriminantGroup L := Submodule.mkQ (latticeInDual L)
  let mkQAdd : DualLattice L →+ DiscriminantGroup L := mkQ.toAddMonoidHom
  have hmap_mkQ : AddSubgroup.map mkQAdd P.toAddSubgroup = H.toAddSubgroup := by
    have hm : Submodule.map mkQ P = H := by
      simp [P, mkQ, map_mkQ_preimageSubmodule]
    simpa [Submodule.map_toAddSubgroup, mkQAdd, mkQ] using congrArg Submodule.toAddSubgroup hm
  have hker_mkQ : mkQAdd.ker = (latticeInDual L).toAddSubgroup := by
    ext x
    simp [mkQAdd, mkQ]
  have hrelIndex_P :
      (latticeInDual L).toAddSubgroup.relIndex P.toAddSubgroup = Nat.card H := by
    simpa [hker_mkQ, hmap_mkQ] using (AddSubgroup.relIndex_ker (K := P.toAddSubgroup) mkQAdd)
  -- Transport the index computation from `ℝ²⁴` to `DualLattice L` using `relIndex_comap`.
  have hrelIndex :
      L.toAddSubgroup.relIndex (AddSubgroup.map inclAdd P.toAddSubgroup) =
        (latticeInDual L).toAddSubgroup.relIndex P.toAddSubgroup := by
    simpa [hcomap_incl] using
      (AddSubgroup.relIndex_comap (H := L.toAddSubgroup) (K := P.toAddSubgroup) (f := inclAdd)).symm
  -- Put everything together (and unfold `P`/`incl` to match the statement).
  have :
      L.toAddSubgroup.relIndex (P.map incl).toAddSubgroup = Nat.card H := by
    rw [hmap_incl, hrelIndex, hrelIndex_P]
  simpa [P, incl] using this

/-- Construct a unimodular overlattice from centers once the relevant subgroup has size
`S.numReps`. -/
public theorem covolume_eq_one_of_covolume_eq_numReps_and_subgroup_card
    (S : PeriodicSpherePacking 24)
    (hCovol : ZLattice.covolume S.lattice MeasureTheory.volume = (S.numReps : ℝ))
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers)
    (hLdual :
      S.lattice ≤
        LinearMap.BilinForm.dualSubmodule (B := (innerₗ ℝ²⁴ : LinearMap.BilinForm ℝ ℝ²⁴))
          S.lattice) :
    ∃ L' : Submodule ℤ ℝ²⁴,
      -- `L'` is an overlattice of `S.lattice`
      S.lattice ≤ L' ∧
      -- unimodularity
      ZLattice.covolume L' MeasureTheory.volume = 1 ∧
      -- and `S.centers` is a single coset of `L'` (i.e. `S` is a lattice packing after recentering)
      ∃ x0' : ℝ²⁴, (S.centers : Set ℝ²⁴) = x0' +ᵥ (L' : Set ℝ²⁴) := by
  -- Rewrite the dual-lattice hypothesis in our abbreviation.
  have hLdual' : S.lattice ≤ DualLattice S.lattice := by
    simpa [Uniqueness.RigidityClassify.DualLattice] using hLdual
  -- Finiteness of the discriminant group (hence `Fintype` on the discriminant group and subgroup).
  haveI : Finite (DiscriminantGroup S.lattice) :=
    finite_discriminantGroup_of_le_dual (L := S.lattice) (hLdual := hLdual)
  let G := DiscriminantGroup S.lattice
  letI : Fintype G := Fintype.ofFinite G
  let H : Submodule ℤ G := centersSubgroup (S := S) hSpec hDens x0
  letI : Fintype H := Fintype.ofFinite H
  -- The map `orbitCoset` lands in `H` by construction.
  let orbitToH : Quotient S.addAction.orbitRel → H :=
    orbitToCentersSubgroup (S := S) hSpec hDens x0
  have horbitToH_inj : Function.Injective orbitToH := by
    simpa [orbitToH, H] using
      (orbitToCentersSubgroup_injective (S := S) (hSpec := hSpec) (hDens := hDens) (x0 := x0))
  -- Lower bound: the generated subgroup has at least `numReps` elements.
  have hcard_numReps_le : S.numReps ≤ Fintype.card H := by
    simpa [PeriodicSpherePacking.numReps] using
      (Fintype.card_le_of_injective orbitToH horbitToH_inj)
  -- Upper bound: isotropic subgroup bound + discriminant-group cardinality.
  -- Build the pairing as an additive bihomomorphism, and use nondegeneracy in the left variable.
  let pairLin : G →ₗ[ℤ] G →ₗ[ℤ] AddCircle (1 : ℝ) := discPair (L := S.lattice)
  let pair : G →+ G →+ AddCircle (1 : ℝ) :=
    { toFun := fun a => (pairLin a).toAddMonoidHom
      map_zero' := by
        ext b
        simp [pairLin]
      map_add' := by
        intro a₁ a₂
        ext b
        simp [pairLin] }
  have hnondeg :
      ∀ a : G, (∀ b : G, pair a b = 0) → a = 0 := by
    intro a ha
    have ha' : ∀ b : G, discPair (L := S.lattice) a b = 0 := by
      intro b
      simpa [pair, pairLin] using ha b
    simpa using (Uniqueness.RigidityClassify.discPair_eq_zero_forall_iff (L := S.lattice) a).1 ha'
  have hIso :
      ∀ a ∈ H.toAddSubgroup, ∀ b ∈ H.toAddSubgroup, pair a b = 0 := by
    intro a ha b hb
    have : discPair (L := S.lattice) a b = 0 :=
      discPair_eq_zero_of_mem_centersSubgroup (S := S) (hSpec := hSpec) (hDens := hDens) (x0 := x0)
        (ha := ha) (hb := hb)
    simpa [pair, pairLin] using this
  have hsq_le : (Fintype.card H) ^ 2 ≤ Fintype.card G := by
    -- `card_isotropic_sq_le` is stated for `AddSubgroup`s.
    simpa using
      (SpherePacking.Dim24.Uniqueness.RigidityClassify.FinitePairing.card_isotropic_sq_le
        (G := G) (pair := pair) hnondeg H.toAddSubgroup hIso)
  have hcardG_real : (Nat.card G : ℝ) = (S.numReps : ℝ) ^ 2 := by
    simpa [hCovol] using
      (Uniqueness.RigidityClassify.card_discriminantGroup_eq_covolume_sq
        (L := S.lattice) (hLdual := hLdual'))
  have hcardG : Fintype.card G = S.numReps ^ 2 := by
    -- convert the real equality to a nat equality
    have : (Fintype.card G : ℝ) = (S.numReps : ℝ) ^ 2 := by
      simpa [Nat.card_eq_fintype_card] using hcardG_real
    exact_mod_cast this
  have hcard_H_le : Fintype.card H ≤ S.numReps := by
    -- compare squares, then take square roots in `ℕ`.
    have hsq : (Fintype.card H) ^ 2 ≤ (S.numReps) ^ 2 := by
      simpa [hcardG] using hsq_le
    -- `m^2 ≤ n^2 ↔ m ≤ n` for naturals.
    exact (Nat.mul_self_le_mul_self_iff).1 (by simpa [pow_two] using hsq)
  have hcardH_eq : Fintype.card H = S.numReps :=
    le_antisymm hcard_H_le hcard_numReps_le
  -- Define the unimodular overlattice.
  let L' : Submodule ℤ ℝ²⁴ := centersOverlattice (S := S) hSpec hDens x0
  have hLL' : S.lattice ≤ L' :=
    lattice_le_centersOverlattice_of_lattice_le_dual (S := S) (hSpec := hSpec) (hDens := hDens)
      (x0 := x0) (hLdual := hLdual')
  -- Discreteness and full-rank for `L'` (to use the covolume/index relation).
  haveI : DiscreteTopology (DualLattice S.lattice) := discreteTopology_dualLattice (L := S.lattice)
  haveI : IsZLattice ℝ (DualLattice S.lattice) := isZLattice_dualLattice (L := S.lattice)
  have hL'_le_dual : L' ≤ DualLattice S.lattice := by
    intro v hv
    rcases hv with ⟨x, hx, rfl⟩
    exact x.2
  -- Embed `L'` into the discrete dual lattice.
  let incl : L' → DualLattice S.lattice := fun x =>
    ⟨(x : ℝ²⁴), hL'_le_dual x.property⟩
  have hcont : Continuous incl := by
    fun_prop
  have hinj : Function.Injective incl := by
    intro x y hxy
    apply Subtype.ext
    exact congrArg (fun z : DualLattice S.lattice => (z : ℝ²⁴)) hxy
  haveI : DiscreteTopology L' :=
    DiscreteTopology.of_continuous_injective (β := DualLattice S.lattice) hcont hinj
  haveI : IsZLattice ℝ L' :=
    isZLattice_of_le_of_isZLattice (L := S.lattice) (L' := L') hLL'
  -- Compute the index `covol(L) / covol(L')` via `relIndex` and show it equals `numReps`.
  have hnumReps_ne : (S.numReps : ℝ) ≠ 0 := by
    have : (S.numReps : ℕ) ≠ 0 := by
      -- `Quotient.mk'' x0` witnesses nonemptiness of the orbit quotient.
      have : Nonempty (Quotient S.addAction.orbitRel) := ⟨Quotient.mk'' x0⟩
      simp [PeriodicSpherePacking.numReps]
    exact Nat.cast_ne_zero.2 this
  -- The relative index is the cardinality of the subgroup `H` (overlattice/index computation).
  have hrelIndex :
      S.lattice.toAddSubgroup.relIndex L'.toAddSubgroup = Fintype.card H := by
    have hnat :
        S.lattice.toAddSubgroup.relIndex L'.toAddSubgroup = Nat.card H := by
      simpa [L', centersOverlattice, H] using
        (relIndex_preimageOverlattice_eq_card (L := S.lattice) (H := H))
    simpa [Nat.card_eq_fintype_card] using hnat
  have hrelIndex_real :
      (S.lattice.toAddSubgroup.relIndex L'.toAddSubgroup : ℝ) = (S.numReps : ℝ) := by
    -- rewrite the index as `card H = numReps`
    have : S.lattice.toAddSubgroup.relIndex L'.toAddSubgroup = S.numReps := by
      simpa [hcardH_eq] using hrelIndex
    exact_mod_cast this
  have hratio :
      ZLattice.covolume S.lattice MeasureTheory.volume /
        ZLattice.covolume L' MeasureTheory.volume =
          (S.lattice.toAddSubgroup.relIndex L'.toAddSubgroup : ℝ) := by
    simpa using
      (ZLattice.covolume_div_covolume_eq_relIndex' (L₁ := S.lattice) (L₂ := L') (h := hLL'))
  have hCovol' : ZLattice.covolume L' MeasureTheory.volume = 1 := by
    -- From `covol(L)/covol(L') = numReps` and `covol(L)=numReps`, deduce `covol(L')=1`.
    have hcovol_ne : ZLattice.covolume L' MeasureTheory.volume ≠ 0 :=
      ZLattice.covolume_ne_zero (L := L') (μ := MeasureTheory.volume)
    have hEq : (S.numReps : ℝ) / ZLattice.covolume L' MeasureTheory.volume = (S.numReps : ℝ) := by
      simpa [hCovol, hrelIndex_real] using hratio
    have hmul : (S.numReps : ℝ) = (S.numReps : ℝ) * ZLattice.covolume L' MeasureTheory.volume :=
      (div_eq_iff hcovol_ne).1 hEq
    exact (mul_eq_left₀ hnumReps_ne).mp (id (Eq.symm hmul))
  -- Finally, show that `S.centers` is exactly one coset of `L'`.
  have hsubset : (S.centers : Set ℝ²⁴) ⊆ (x0 : ℝ²⁴) +ᵥ (L' : Set ℝ²⁴) :=
    centers_subset_vadd_centersOverlattice (S := S) (hSpec := hSpec) (hDens := hDens) (x0 := x0)
  -- Use cardinality to upgrade injectivity of `orbitToH` to surjectivity.
  have horbitToH_surj : Function.Surjective orbitToH := by
    by_contra hnsurj
    have hlt :=
      Fintype.card_lt_of_injective_not_surjective orbitToH horbitToH_inj hnsurj
    -- `card domain = numReps` and `card codomain = numReps`
    have hEq : Fintype.card (Quotient S.addAction.orbitRel) = Fintype.card H := by
      simp [PeriodicSpherePacking.numReps, hcardH_eq]
    exact (lt_irrefl _ (hEq ▸ hlt))
  have hsuperset : (x0 : ℝ²⁴) +ᵥ (L' : Set ℝ²⁴) ⊆ (S.centers : Set ℝ²⁴) :=
    vadd_centersOverlattice_subset_centers_of_surjective S hSpec hDens x0 horbitToH_surj
  refine ⟨L', hLL', hCovol', (x0 : ℝ²⁴), ?_⟩
  exact Set.Subset.antisymm hsubset hsuperset

end

end SpherePacking.Dim24.Uniqueness.RigidityClassify
