module
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.CodeFromOctads.Span
import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.CodeFromOctads.OctadsEq

/-!
# Reducing `permuteCode` equality to octads

This file isolates the step where equality of permuted codes is reduced to:
* an equality of octad sets (supports of weight-8 words), and
* a hypothesis that each code is generated by its octads.

The coding-theoretic input (generation by octads) is provided in later files; here we only
transport submodules along coordinate permutations.
-/

namespace SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniquenessSteps.CodeFromOctads

noncomputable section

open LinearCode

private lemma submodule_permuteCode_eq_map
    (σ : Equiv (Fin 24) (Fin 24)) (C : Code 24) (hC : IsLinearCode C) :
    submodule (n := 24) (permuteCode (n := 24) σ C)
        (isLinearCode_permuteCode (σ := σ) (C := C) hC) =
      (submodule (n := 24) C hC).map (permuteLinearEquiv σ).toLinearMap := by
  ext w
  grind (splits := 2) only [= LinearCode.mem_submodule, Submodule.mem_map, = mem_permuteCode_iff]

/--
If both codes are generated by their octads, then an equality `hoct` of transported octad sets
forces the whole code to agree after an appropriate coordinate permutation.
-/
public lemma permuteCode_eq_of_octads_eq_of_generated_by_octads
    (C₁ C₂ : Code 24)
    (h₁ : IsLinearCode C₁)
    (h₂ : IsLinearCode C₂)
    (σ : Equiv (Fin 24) (Fin 24))
    (hoct : octadsFromCode C₁ = {B | (Finset.map σ.toEmbedding B) ∈ octadsFromCode C₂})
    (hgen₁ : submodule (n := 24) C₁ h₁ = octadSubmodule C₁)
    (hgen₂ : submodule (n := 24) C₂ h₂ = octadSubmodule C₂) :
    permuteCode (n := 24) σ.symm C₁ = C₂ := by
  have hsub :
      submodule (n := 24) (permuteCode (n := 24) σ.symm C₁)
          (isLinearCode_permuteCode (σ := σ.symm) (C := C₁) h₁) =
        submodule (n := 24) C₂ h₂ := by
    calc
      submodule (n := 24) (permuteCode (n := 24) σ.symm C₁)
            (isLinearCode_permuteCode (σ := σ.symm) (C := C₁) h₁)
          = (submodule (n := 24) C₁ h₁).map (permuteLinearEquiv σ.symm).toLinearMap := by
              simpa using submodule_permuteCode_eq_map (σ := σ.symm) (C := C₁) h₁
      _ = (octadSubmodule C₁).map (permuteLinearEquiv σ.symm).toLinearMap := by simp [hgen₁]
      _ = octadSubmodule C₂ := by
            -- In `OctadsEq` we map by `σ.symm` since `permuteWord σ.symm` maps supports by `σ`.
            simpa using (octadSubmodule_map_eq_of_octads_eq (C₁ := C₁) (C₂ := C₂) (σ := σ) hoct)
      _ = submodule (n := 24) C₂ h₂ := by simp [hgen₂]
  ext w
  have :
      w ∈
          submodule (n := 24) (permuteCode (n := 24) σ.symm C₁)
            (isLinearCode_permuteCode (σ := σ.symm) (C := C₁) h₁) ↔
      w ∈ submodule (n := 24) C₂ h₂ := by
    simp [hsub]
  simpa [LinearCode.mem_submodule] using this

end

end SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniquenessSteps.CodeFromOctads
