module
public import SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.CodeFromLattice
public import SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma20.ContainsDn
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayDefs
public import SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.Shell4.Bridge
import SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.Isometry.CodeIsGolayCountFinal
import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayConcrete
import SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.Isometry.GolayOctadGeneration

/-!
# Auxiliary lemmas for shell isometries

This file packages the coding-theoretic consequences of the BS81 Lemma 21 forcing step as named
lemmas used in the "coding theory to geometry" bridge.

## Main statements
* `isExtendedBinaryGolayCode_codeFromLattice`
* `Shell4IsometryAux.exists_perm24_equiv_leechParityCode_of_isExtendedBinaryGolayCode`
* `Shell4IsometryAux.exists_linearIsometry_shell4_to_leech_of_code_equiv`
-/


namespace SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.IsometrySteps

noncomputable section

open scoped RealInnerProductSpace

open Uniqueness.BS81
open Uniqueness.BS81.CodingTheory
open Uniqueness.BS81.Thm15.Lemma21

local notation "ℝ²⁴" => EuclideanSpace ℝ (Fin 24)

/-- In the equality case, the extracted code `codeFromLattice` is an extended binary Golay code. -/
public theorem isExtendedBinaryGolayCode_codeFromLattice
    (C : Set ℝ²⁴) (hEq : Uniqueness.BS81.Thm14.EqCase24Pkg C)
    (hDn : Uniqueness.BS81.Thm15.Lemma20.ContainsDn C 24) :
    Uniqueness.BS81.CodingTheory.IsExtendedBinaryGolayCode
      (CodeFromLattice.codeFromLattice (C := C) hDn) := by
  have h := CodeIsGolayCountFinal.forcing_parameters_codeFromLattice (C := C) hEq hDn
  exact ⟨CodeFromLattice.codeFromLattice_linear (C := C) hDn, h.1, h.2.2⟩

namespace Shell4IsometryAux

/-!
## Coding-theory alignment interface

The proof proceeds as follows:

1. From BS81 Lemma 21 forcing, show the extracted code is an extended binary Golay code.
2. Use uniqueness to identify it with the concrete Golay code up to coordinate
   permutation.
3. Translate this coordinate permutation into a linear isometry of `ℝ²⁴`.
4. Prove that under this isometry, the shell-4 vectors correspond to the Leech minimal vectors.

We isolate these steps as named lemmas below.
-/

/-- Identify an extended binary Golay code with the concrete one, up to permutation. -/
theorem exists_perm24_equiv_concrete_of_isExtendedBinaryGolayCode
    (C : Code 24) (hC : IsExtendedBinaryGolayCode C) :
    ∃ σ : Equiv (Fin 24) (Fin 24), permuteCode (n := 24) σ C = extendedBinaryGolayConcrete := by
  -- Provide the "generated by octads" hypotheses required by `extendedBinaryGolay_unique`.
  have hgen₁ :
      LinearCode.submodule (n := 24) C hC.linear =
        GolayUniquenessSteps.CodeFromOctads.octadSubmodule C :=
    GolayOctadGeneration.codeSubmodule_eq_octadSubmodule_of_isExtendedBinaryGolayCode (C := C) hC
  have hGolayConcrete : IsExtendedBinaryGolayCode extendedBinaryGolayConcrete :=
    isExtendedBinaryGolayCode_extendedBinaryGolayConcrete
  have hgen₂ :
      LinearCode.submodule (n := 24) extendedBinaryGolayConcrete hGolayConcrete.linear =
        GolayUniquenessSteps.CodeFromOctads.octadSubmodule extendedBinaryGolayConcrete :=
    GolayOctadGeneration.codeSubmodule_eq_octadSubmodule_of_isExtendedBinaryGolayCode
      (C := extendedBinaryGolayConcrete) hGolayConcrete
  exact extendedBinaryGolay_unique C extendedBinaryGolayConcrete hC hGolayConcrete hgen₁ hgen₂

/-- Convert an identification with the concrete Golay code into an identification with the Leech
parity code. -/
public theorem exists_perm24_equiv_leechParityCode_of_isExtendedBinaryGolayCode
    (C : Code 24) (hC : IsExtendedBinaryGolayCode C) :
    ∃ σ : Equiv (Fin 24) (Fin 24),
      permuteCode (n := 24) σ C = Shell4IsometryLeechParityCode.leechParityCode := by
  rcases exists_perm24_equiv_concrete_of_isExtendedBinaryGolayCode (C := C) hC with ⟨σ0, hσ0⟩
  refine ⟨Shell4IsometryLeechParityCode.leechGolayPerm.trans σ0, ?_⟩
  simpa [permuteCode_trans, hσ0] using
    (Shell4IsometryLeechParityCode.leechParityCode_eq_leechGolayCode).symm

/-!
## Geometry interface: code alignment ⇒ shell isometry

This is the "bridge" from coding data to the geometric statement used by BS81 Lemma 21.
It should be proved by:

* choosing the `D₂₄` frame from `ContainsDn`;
* mapping it to the standard basis via an `OrthonormalBasis`;
* using the code equivalence to match the coordinate patterns for the norm-4 shell;
* concluding membership in `LeechLattice` via the explicit generator matrix definition.
-/

/-- A code alignment yields a linear isometry sending the shell-4 set to the Leech shell. -/
public theorem exists_linearIsometry_shell4_to_leech_of_code_equiv
    (Cset : Set ℝ²⁴)
    (hEq : Uniqueness.BS81.Thm14.EqCase24Pkg Cset)
    (hDn : Uniqueness.BS81.Thm15.Lemma20.ContainsDn Cset 24)
    (σ : Equiv (Fin 24) (Fin 24))
    (hσ :
      permuteCode (n := 24) σ (CodeFromLattice.codeFromLattice (C := Cset) hDn) =
        Shell4IsometryLeechParityCode.leechParityCode)
    (base : OddBasepointRowLast (Cset := Cset) hDn σ) :
    ∃ e : ℝ²⁴ ≃ₗᵢ[ℝ] ℝ²⁴, e '' (latticeShell4 Cset) = leechShell4 := by
  let e : ℝ²⁴ ≃ₗᵢ[ℝ] ℝ²⁴ := shell4Isometry (C := Cset) hDn σ
  refine ⟨e, ?_⟩
  -- Hard step: membership in the Leech lattice for the transported shell.
  have hsubset :
      e '' latticeShell4 Cset ⊆ leechShell4 :=
    image_shell4_subset_leechShell4_of_code_equiv
      (Cset := Cset) (hEq := hEq) (hDn := hDn) (σ := σ) (hσ := hσ) (base := base)
  -- Cardinalities: both sets have size `196560`.
  have hncard_left : Set.ncard (e '' latticeShell4 Cset) = 196560 := by
    -- `e` is injective, so `ncard` is preserved under images.
    calc
      Set.ncard (e '' latticeShell4 Cset) = Set.ncard (latticeShell4 Cset) := by
        simpa [e] using
          (Set.ncard_image_of_injective (s := latticeShell4 Cset) (f := e) e.injective)
      _ = 196560 := ncard_latticeShell4_eq_196560 (C := Cset) hEq
  have hncard_right : Set.ncard (leechShell4) = 196560 :=
    ncard_leechShell4
  have hncard_right_le : Set.ncard leechShell4 ≤ Set.ncard (e '' latticeShell4 Cset) := by
    simp [hncard_left, hncard_right]
  have hfin_leech : leechShell4.Finite := by
    refine Set.finite_of_ncard_ne_zero ?_
    simp [hncard_right]
  -- Conclude by subset + cardinality.
  exact Set.eq_of_subset_of_ncard_le hsubset hncard_right_le hfin_leech

end Shell4IsometryAux

end

end SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.IsometrySteps
