module
public import Mathlib.Algebra.Field.ZMod
public import Mathlib.LinearAlgebra.Matrix.FixedDetMatrices
public import Mathlib.NumberTheory.ModularForms.CongruenceSubgroups
public import Mathlib.NumberTheory.ModularForms.SlashActions

/-!
# Slash action generators for `SL(2, ℤ)` and `Γ(2)`

This file defines standard elements in `Γ(2)` and proves generator lemmas that reduce
slash-invariance checks to those generators.

## Main definitions
* `negI`, `α`, `β`

## Main statements
* `SL2Z_generate`
* `slashaction_generators_SL2Z`
* `slashaction_generators_GL2R`
* `slashaction_generators_Γ2`
-/


open scoped ModularForm MatrixGroups
open Matrix UpperHalfPlane CongruenceSubgroup ModularGroup

local notation "Γ " n:100 => Gamma n

private lemma zmod_two_natCast_self : (2 : ZMod 2) = 0 := by
  simpa using ZMod.natCast_self 2

/-- The element `-I` of `Γ(2)`. -/
@[expose] public def negI : Γ 2 := ⟨⟨!![-1, 0; 0, -1], by simp⟩, by simp⟩

/-- The standard generator `α = [[1,2],[0,1]]` of `Γ(2)`. -/
@[expose] public def α : Γ 2 :=
  ⟨⟨!![1, 2; 0, 1], by simp⟩, by
    simp [Gamma_mem, zmod_two_natCast_self]⟩

/-- The standard generator `β = [[1,0],[2,1]]` of `Γ(2)`. -/
@[expose] public def β : Γ 2 :=
  ⟨⟨!![1, 0; 2, 1], by simp⟩, by
    simp [Gamma_mem, zmod_two_natCast_self]⟩

/-- Identify `α` with `T^2` in `SL(2, ℤ)` (as an element of `Γ(2)`). -/
public theorem α_eq_T_sq :
    α = ⟨T ^ 2, by
      simpa using
        (ModularGroup_T_pow_mem_Gamma (N := (2 : ℤ)) (M := (2 : ℤ)) (dvd_rfl : (2 : ℤ) ∣ 2))⟩ := by
  ext
  simp [α, T, pow_two]

/-- Express `β` in terms of `α`, `S` and `negI`. -/
public theorem β_eq_negI_mul_S_mul_α_inv_mul_S : β = negI * S * α⁻¹ * S := by
  ext
  simp [β, S, α, negI]

theorem ModularGroup.modular_negI_sq : negI ^ 2 = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;> rfl

/-- In `Γ(2)`, the element `negI` is self-inverse. -/
public theorem ModularGroup.modular_negI_inv : negI⁻¹ = negI := by
  ext i j
  simp [negI]

namespace ModularForm

/-- A specialized `mul_slash_SL2` lemma with weights `2` and `4`. -/
public lemma mul_slash_SL2_2_4 (A : SL(2, ℤ)) (f g : ℍ → ℂ) :
    (f * g) ∣[(6 : ℤ)] A = f ∣[(2 : ℤ)] A * g ∣[(4 : ℤ)] A := by
  simpa using (mul_slash_SL2 (k1 := 2) (k2 := 4) A f g)

end ModularForm

section slash_action

variable (f : ℍ → ℂ) (k : ℤ) (z : ℍ)

open ModularForm

theorem modular_negI_smul : negI.1 • z = z := by
  simp [specialLinearGroup_apply, negI]

/-- If `k` is even, then the slash action by `-I` is the identity. -/
public theorem modular_slash_negI_of_even (hk : Even k) : f ∣[k] negI.1 = f := by
  ext x
  rw [slash_action_eq'_iff, modular_negI_smul]
  simp [negI, hk.neg_one_zpow]

/-- Evaluate the slash action by `S` explicitly. -/
public theorem modular_slash_S_apply :
    (f ∣[k] S) z = f (UpperHalfPlane.mk (-z)⁻¹ z.im_inv_neg_coe_pos) * z ^ (-k) := by
  rw [SL_slash_apply, denom, UpperHalfPlane.modular_S_smul]
  simp [S]

/-- Evaluate the slash action by `T` explicitly. -/
public theorem modular_slash_T_apply : (f ∣[k] T) z = f ((1 : ℝ) +ᵥ z) := by
  rw [SL_slash_apply, denom, UpperHalfPlane.modular_T_smul]
  simp [T]

end slash_action

section slashaction_generators

/- This part proves that `SL(2, ℤ)` and `Γ 2` are generated by `{S, T, -I}` and `{α, β, -I}`
respectively. -/

/-- The group `SL(2, ℤ)` is generated by `S` and `T`. -/
public theorem SL2Z_generate : (⊤ : Subgroup SL(2, ℤ)) = Subgroup.closure {S, T} := by
  simpa using SpecialLinearGroup.SL2Z_generators.symm

private lemma mem_closure_α : α ∈ Subgroup.closure {α, β, negI} :=
  Subgroup.subset_closure (Set.mem_insert _ _)

private lemma mem_closure_β : β ∈ Subgroup.closure {α, β, negI} :=
  Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_insert _ _))

private lemma mem_closure_negI : negI ∈ Subgroup.closure {α, β, negI} :=
  Subgroup.subset_closure (Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ rfl))

private lemma α_zpow_mem_closure (k : ℤ) : α ^ k ∈ Subgroup.closure {α, β, negI} :=
  Subgroup.zpow_mem _ mem_closure_α k

private lemma β_zpow_mem_closure (k : ℤ) : β ^ k ∈ Subgroup.closure {α, β, negI} :=
  Subgroup.zpow_mem _ mem_closure_β k

private lemma inv_α_zpow_mem_closure (k : ℤ) : (α ^ k)⁻¹ ∈ Subgroup.closure {α, β, negI} :=
  Subgroup.inv_mem _ (α_zpow_mem_closure k)

private lemma β_zpow_mul_α_zpow_mem_closure (m n : ℤ) :
    β ^ m * α ^ n ∈ Subgroup.closure {α, β, negI} :=
  Subgroup.mul_mem _ (β_zpow_mem_closure m) (α_zpow_mem_closure n)

private lemma SL2_coe_mul (A B : SL(2, ℤ)) :
    ((A * B : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) =
      (A : Matrix (Fin 2) (Fin 2) ℤ) * (B : Matrix (Fin 2) (Fin 2) ℤ) := by
  simp [SpecialLinearGroup.coe_mul]

private lemma SL2_coe_inv (A : SL(2, ℤ)) :
    ((A⁻¹ : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) = adjugate (A : Matrix (Fin 2) (Fin 2) ℤ) := by
  simp [SpecialLinearGroup.coe_inv]

/-- The matrix `α ^ k` equals `[[1, 2k], [0, 1]]`. -/
theorem α_zpow_val (k : ℤ) : (α ^ k : SL(2, ℤ)).val = !![1, 2 * k; 0, 1] := by
  have hα : (α : SL(2, ℤ)) = T ^ (2 : ℤ) := by
    ext i j; fin_cases i <;> fin_cases j <;> simp [α, ModularGroup.coe_T_zpow]
  have hk : (α ^ k : SL(2, ℤ)) = T ^ (2 * k) := by
    simp [hα, zpow_mul]
  simpa using (show ((α ^ k : SL(2, ℤ)) : Matrix (Fin 2) (Fin 2) ℤ) = !![1, 2 * k; 0, 1] from by
    simpa [hk] using (ModularGroup.coe_T_zpow (2 * k)))

/-- The `(1, 0)` entry of `α ^ k` is always `0`. -/
theorem α_zpow_one_zero (k : ℤ) : (α ^ k : SL(2, ℤ)).val 1 0 = 0 := by simp [α_zpow_val]

/-- The matrix `β ^ k` equals `[[1, 0], [2k, 1]]`. -/
theorem β_zpow_val (k : ℤ) : (β ^ k : SL(2, ℤ)).val = !![1, 0; 2 * k, 1] := by
  induction k using Int.induction_on with
  | zero => exact Matrix.one_fin_two
  | succ n ih =>
    simp only [zpow_add, zpow_one, SL2_coe_mul, ih]
    ext i j; fin_cases i <;> fin_cases j <;> simp [β, Matrix.mul_apply]; ring
  | pred n ih =>
    simp only [zpow_sub, zpow_one, SL2_coe_mul, SL2_coe_inv, adjugate_fin_two, ih]
    ext i j; fin_cases i <;> fin_cases j <;> simp [β, Matrix.mul_apply]; ring

lemma Γ2_c_eq_zero (A : Γ 2) (h : A.1 1 0 = 0) : A ∈ Subgroup.closure {α, β, negI} := by
  rcases A with ⟨val, property⟩
  have h10 : val.val 1 0 = 0 := by simpa using h
  have hk : ∃ k : ℤ, val.val 0 1 = 2 * k := by
    have hΓ : (val.val 0 0 : ZMod 2) = 1 ∧ (val.val 0 1 : ZMod 2) = 0 ∧
        (val.val 1 0 : ZMod 2) = 0 ∧ (val.val 1 1 : ZMod 2) = 1 := by
      simpa [Gamma_mem] using property
    have h01 : (2 : ℤ) ∣ val.val 0 1 := by
      simpa [ZMod.intCast_zmod_eq_zero_iff_dvd] using hΓ.2.1
    rcases h01 with ⟨k, hk⟩
    exact ⟨k, hk⟩
  rcases hk with ⟨k, hk⟩
  have hdet : val.val 0 0 * val.val 1 1 = 1 := by
    have hdet := val.2
    rw [Matrix.det_fin_two] at hdet
    simpa [h10] using hdet
  rcases Int.mul_eq_one_iff_eq_one_or_neg_one.1 hdet with ⟨ha, h11⟩ | ⟨ha, h11⟩
  · have hA : (⟨val, property⟩ : Γ 2) = α ^ k := by
      ext i j
      fin_cases i <;> fin_cases j <;> simp [α_zpow_val, ha, h11, h10, hk]
    simpa [hA] using α_zpow_mem_closure k
  · have hA : (⟨val, property⟩ : Γ 2) = negI * α ^ (-k) := by
      ext i j
      fin_cases i <;> fin_cases j <;> simp [α_zpow_val, ha, h11, h10, hk, negI]
    refine hA ▸ Subgroup.mul_mem _ mem_closure_negI (α_zpow_mem_closure (-k))

lemma Γ2_reduce_row (a c : ℤ) (ha : Odd a) (hc : Even c) (hc0 : c ≠ 0) :
    ∃ n, |a + 2 * n * c| < |c| := by
  have h2c : 2 * c ≠ 0 := by simp [hc0]
  obtain ⟨q, r, hqr, hr0, hr2c⟩ : ∃ q r, a = 2 * c * q + r ∧ 0 ≤ r ∧ r < 2 * |c| := by
    refine ⟨a / (2 * c), a % (2 * c), by rw [Int.mul_ediv_add_emod],
      Int.emod_nonneg _ h2c, ?_⟩
    simpa using Int.emod_lt_abs _ h2c
  by_cases hr_le : r ≤ |c|
  · refine ⟨-q, ?_⟩
    by_cases hr_eq : r = c ∨ r = -c <;> [grind; exact abs_lt.mpr ⟨by grind, by grind⟩]
  · refine ⟨-q - (if c > 0 then 1 else -1), ?_⟩
    split_ifs <;> cases abs_cases c <;> grind

lemma Γ2_reduce_col (a c : ℤ) (ha : Odd a) (hc : Even c) (ha0 : a ≠ 0) :
    ∃ m, |c + 2 * m * a| < |a| := by
  obtain ⟨q, r, hqr, hr0, hra⟩ : ∃ q r, c / 2 = q * a + r ∧ 0 ≤ r ∧ r < |a| :=
    ⟨c / 2 / a, c / 2 % a, by rw [Int.ediv_mul_add_emod],
      Int.emod_nonneg _ ha0, Int.emod_lt_abs _ ha0⟩
  obtain ⟨m, hm⟩ : ∃ m, |c / 2 + m * a| ≤ (|a| - 1) / 2 := by
    by_cases hr_case : r ≤ (|a| - 1) / 2
    · exact ⟨-q, by rw [abs_le]; constructor <;> grind⟩
    · refine ⟨if a > 0 then -q - 1 else -q + 1, ?_⟩
      split_ifs <;> cases abs_cases a <;> cases ha <;> exact abs_le.mpr ⟨by grind, by grind⟩
  refine ⟨m, ?_⟩
  grind only [= Int.even_iff, = abs.eq_1, = max_def]

/-- The `(0, 0)` entry of any element of `Γ(2)` is odd. -/
lemma Γ2_odd_00 (A : Γ 2) : Odd (A.val.val 0 0) := by
  have hΓ := (Gamma_mem (N := 2) (γ := A.1)).1 A.2
  exact (ZMod.intCast_eq_one_iff_odd (n := A.val.val 0 0)).1 hΓ.1
/-- The `(1, 0)` entry of any element of `Γ(2)` is even. -/
lemma Γ2_even_10 (A : Γ 2) : Even (A.val.val 1 0) := by
  have hΓ := (Gamma_mem (N := 2) (γ := A.1)).1 A.2
  exact even_iff_two_dvd.2 (by simpa [ZMod.intCast_zmod_eq_zero_iff_dvd] using hΓ.2.2.1)

lemma Γ2_descent (A : Γ 2) (h : A.1 1 0 ≠ 0) :
    ∃ (M : Γ 2), M ∈ Subgroup.closure {α, β, negI} ∧ |(M * A).1 1 0| < |A.1 1 0| := by
  have h_odd := Γ2_odd_00 A
  have h_even := Γ2_even_10 A
  obtain ⟨n, hn⟩ := Γ2_reduce_row (A.val.val 0 0) (A.val.val 1 0) h_odd h_even (by simpa using h)
  have ha'_odd : Odd (A.val.val 0 0 + 2 * n * A.val.val 1 0) := by simp [parity_simps, h_odd]
  have ha'_ne : A.val.val 0 0 + 2 * n * A.val.val 1 0 ≠ 0 := by
    rcases ha'_odd with ⟨t, ht⟩
    refine ht ▸ by omega
  obtain ⟨m, hm⟩ := Γ2_reduce_col _ _ ha'_odd h_even ha'_ne
  refine ⟨β ^ m * α ^ n, β_zpow_mul_α_zpow_mem_closure m n, ?_⟩
  simp only [Subgroup.coe_mul, SubgroupClass.coe_zpow, SpecialLinearGroup.coe_mul,
    α_zpow_val, β_zpow_val, Matrix.mul_apply, Fin.sum_univ_two, Matrix.of_apply,
    Matrix.cons_val_zero, Matrix.cons_val_one] at hn hm ⊢
  convert hm.trans hn using 1
  ring_nf

public theorem Γ2_generate : (⊤ : Subgroup (Γ 2)) = Subgroup.closure {α, β, negI} := by
  refine le_antisymm ?_ le_top
  intro A hA
  by_contra h_contra
  let S : Set ℕ :=
    {n : ℕ | ∃ M ∈ Subgroup.closure {α, β, negI}, n = Int.natAbs ((M * A).val.val 1 0)}
  let d := sInf S
  obtain ⟨M, hM₁, hM₂⟩ :
    ∃ M ∈ Subgroup.closure {α, β, negI}, Int.natAbs ((M * A).val.val 1 0) = d := by
    have h_nonempty : S.Nonempty := ⟨_, ⟨1, Subgroup.one_mem _, rfl⟩⟩
    rcases (Nat.sInf_mem h_nonempty) with ⟨M, hM₁, hM₂⟩
    exact ⟨M, hM₁, by simpa [d] using hM₂.symm⟩
  by_cases hd_pos : d > 0
  · obtain ⟨M', hM'₁, hM'₂⟩ : ∃ M' ∈ Subgroup.closure {α, β, negI},
      Int.natAbs ((M' * (M * A)).val.val 1 0) < d := by
      convert Γ2_descent (M * A) fun h ↦ _ <;> simp_all [← hM₂, ← Int.ofNat_lt]
    have h_inf_le :
      ∀ n ∈ S, d ≤ n := fun n hn ↦ Nat.sInf_le hn
    exact not_lt_of_ge (h_inf_le _ ⟨M' * M, Subgroup.mul_mem _ hM'₁ hM₁, rfl⟩)
      (by simpa [mul_assoc] using hM'₂)
  · have hMA_zero : (M * A).val.val 1 0 = 0 :=
      Int.natAbs_eq_zero.mp (hM₂.trans (le_antisymm (le_of_not_gt hd_pos) (Nat.zero_le _)))
    exact h_contra
      (by simpa only [inv_mul_cancel_left] using
        Subgroup.mul_mem _ (Subgroup.inv_mem _ hM₁) (Γ2_c_eq_zero _ hMA_zero))

/-- If `G` is generated by a set `s`, then the slash action by elements in G is
uniquely determined by the slash action by elements in s. See `slashaction_generators'` for a
version where `s` is a set of elements in `G`. -/
theorem slashaction_generators
    (f : ℍ → ℂ) (G : Subgroup SL(2, ℤ)) (s : Set SL(2, ℤ)) (hG : G = Subgroup.closure s) (k : ℤ) :
    (∀ γ : G, f ∣[k] γ.1 = f) ↔ (∀ γ ∈ s, f ∣[k] γ = f) := by
  subst hG
  constructor <;> intro h
  · intro γ hγ
    convert h ⟨γ, Subgroup.subset_closure hγ⟩
  · rintro ⟨γ, hγ⟩
    refine Subgroup.closure_induction (p := fun γ _ ↦ f ∣[k] γ = f) (k := s) ?_ ?_ ?_ ?_ hγ
    · exact fun x hx => h x hx
    · simp [SlashAction.slash_one]
    · intro _ _ _ _ hf₁ hf₂; simp [SlashAction.slash_mul, hf₁, hf₂]
    · intro x hx hf
      rw [← hf, ← SlashAction.slash_mul, mul_inv_cancel, SlashAction.slash_one, hf]

/-- If `G` is generated by a set `s`, then the slash action by elements in G is
uniquely determined by the slash action by elements in s. See `slashaction_generators` for a
version where `s` is a set of elements in SL(2, ℤ). -/
theorem slashaction_generators'
    (f : ℍ → ℂ) {G : Subgroup SL(2, ℤ)} (s : Set G) (hG : ⊤ = Subgroup.closure s) (k : ℤ) :
    (∀ γ : G, f ∣[k] γ.1 = f) ↔ (∀ γ ∈ s, f ∣[k] γ.1 = f) := by
  constructor <;> intro h
  · intro γ _
    exact h γ
  · intro ⟨γ, hγ⟩
    -- key idea: this lemma allows induction on the "words" of the group
    apply Subgroup.closure_induction (G := G) (p := fun γ _ ↦ f ∣[k] γ.1 = f) (k := s) ?_ ?_
    · intro _ _ _ _ hf₁ hf₂
      rw [@Subgroup.coe_mul, SlashAction.slash_mul, hf₁, hf₂]
    · intro x _ hf
      rw [← hf, ← SlashAction.slash_mul]
      simp [hf]
    · simp [← hG]
    · intro γ hγ
      exact h γ hγ
    · exact SlashAction.slash_one k f

/-- Reduce invariance under `SL(2, ℤ)` to invariance under `S` and `T`. -/
public theorem slashaction_generators_SL2Z
    (f : ℍ → ℂ) (k : ℤ) (hS : f ∣[k] S = f) (hT : f ∣[k] T = f) :
    (∀ γ : SL(2, ℤ), f ∣[k] γ = f) := by
  intro γ
  refine (slashaction_generators f ⊤ {S, T} SL2Z_generate k).2 ?_ ⟨γ, by simp⟩
  rintro γ (rfl | rfl) <;> assumption

/-- Reduce invariance under `Γ(1)` (viewed in `GL(2, ℝ)`) to invariance under `S` and `T`. -/
public theorem slashaction_generators_GL2R
    (f : ℍ → ℂ) (k : ℤ) (hS : f ∣[k] S = f) (hT : f ∣[k] T = f) :
    (∀ γ ∈ Subgroup.map (Matrix.SpecialLinearGroup.mapGL ℝ) (CongruenceSubgroup.Gamma 1),
       f ∣[k] γ = f) := by
  intro γ hγ
  rcases (by simpa [Subgroup.mem_map] using hγ) with ⟨A, -, rfl⟩
  simpa using slashaction_generators_SL2Z f k hS hT A

/--
Reduce invariance under `Γ(2)` (viewed in `GL(2, ℝ)`) to invariance under `α`, `β`, and `negI`.
-/
public theorem slashaction_generators_Γ2
    (f : ℍ → ℂ) (k : ℤ) (hα : f ∣[k] α.1 = f) (hβ : f ∣[k] β.1 = f) (hnegI : f ∣[k] negI.1 = f) :
  (∀ γ ∈ Subgroup.map (SpecialLinearGroup.mapGL ℝ) (Γ 2), f ∣[k] γ = f) := by
  intro γ hγ
  rcases (Subgroup.mem_map.1 hγ) with ⟨A, hA, rfl⟩
  refine (slashaction_generators' f {α, β, negI} Γ2_generate k).mpr ?_ ⟨A, hA⟩
  grind only [= Set.mem_insert_iff, = Set.mem_singleton_iff]

end slashaction_generators
