module
public import
  SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.WittDesignUniqueTheory.BiplaneFromSharp.EvenBasis
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.CodeFromOctadsAux
public import Mathlib.Algebra.BigOperators.Group.Finset.Basic

/-!
# Spanning the even-weight code on a 12-set

In the biplane reduction, we puncture away a dodecad and work on the remaining `12` coordinates.
Over `ZMod 2`, the even-weight code on these coordinates is generated by the `11` weight-`2` words
`t0 + t i` (implemented as `evenBasisFamily t0 t i`). This file proves a spanning lemma for
even-weight words supported on `{t0} ∪ range t`, phrased to apply conveniently after `eraseCoords`.
-/

namespace SpherePacking.Dim24.Uniqueness.BS81.CodingTheory

namespace GolayUniquenessSteps.WittDesignUniqueTheory.EvenBasisSpan

noncomputable section

open scoped BigOperators
open GolayBounds
open GolayUniquenessSteps.CodeFromOctadsAux
open BiplaneFromSharp

/-- Indices `i` such that the coordinate `t i` lies in `support w`. -/
public def idxSupport (t : Fin 11 → Fin 24) (w : BinWord 24) : Finset (Fin 11) :=
  (Finset.univ : Finset (Fin 11)).filter fun i => t i ∈ support w

/-- Membership in `idxSupport` is membership of the corresponding coordinate in `support`. -/
public lemma mem_idxSupport_iff (t : Fin 11 → Fin 24) (w : BinWord 24) (i : Fin 11) :
    i ∈ idxSupport t w ↔ t i ∈ support w := by
  simp [idxSupport]

/-- Evaluate the star-basis word `evenBasisFamily t0 t i` as an indicator of `{t0, t i}`. -/
public lemma evenBasisFamily_apply
    {t0 : Fin 24} {t : Fin 11 → Fin 24} (i : Fin 11) (x : Fin 24) :
    evenBasisFamily t0 t i x = (if x = t0 ∨ x = t i then (1 : ZMod 2) else 0) := by
  simp [BiplaneFromSharp.evenBasisFamily, BiplaneFromSharp.evenBasisWord, wordOfFinset]

attribute [grind =] evenBasisFamily_apply

/-- Summing `evenBasisFamily` over `I` evaluates to `I.card` at the center coordinate `t0`. -/
public lemma sum_evenBasisFamily_apply_t0
    {t0 : Fin 24} {t : Fin 11 → Fin 24} (I : Finset (Fin 11)) :
    (∑ i ∈ I, evenBasisFamily t0 t i) t0 = (I.card : ZMod 2) := by
  simp [evenBasisFamily, evenBasisWord, wordOfFinset]

/-- On the `t`-coordinates, `evenBasisFamily t0 t i` is a Kronecker delta (under injectivity). -/
public lemma evenBasisFamily_apply_t
    {t0 : Fin 24} {t : Fin 11 → Fin 24}
    (htinj : Function.Injective t) (hne : ∀ i, t0 ≠ t i) (i k : Fin 11) :
    evenBasisFamily t0 t i (t k) = (if i = k then (1 : ZMod 2) else 0) := by
  grind only [= evenBasisFamily_apply]

/-- Summing `evenBasisFamily` over `I` picks out membership of the index `k` in `I`. -/
public lemma sum_evenBasisFamily_apply_t
    {t0 : Fin 24} {t : Fin 11 → Fin 24}
    (htinj : Function.Injective t) (hne : ∀ i, t0 ≠ t i)
    (I : Finset (Fin 11)) (k : Fin 11) :
    (∑ i ∈ I, evenBasisFamily t0 t i) (t k) = (if k ∈ I then (1 : ZMod 2) else 0) := by
  simp [Finset.sum_apply, evenBasisFamily_apply_t (t0 := t0) (t := t) htinj hne, eq_comm]

/--
For an even-weight word supported on `{t0} ∪ range t`, membership of `t0` is detected by
parity.
-/
public lemma t0_mem_support_iff_odd_filter_card
    {t0 : Fin 24} {t : Fin 11 → Fin 24}
    (htinj : Function.Injective t) (hne : ∀ i, t0 ≠ t i)
    {w : BinWord 24}
    (hsupp : support w ⊆ insert t0 ((Finset.univ : Finset (Fin 11)).image t))
    (hEven : Even (support w).card) :
    (t0 ∈ support w ↔
      Odd (idxSupport t w).card) := by
  -- Let `I` be the set of indices whose coordinate is `1`.
  let I : Finset (Fin 11) := idxSupport t w
  have hI : ∀ i, i ∈ I ↔ t i ∈ support w := by
    intro i
    simpa [I] using (mem_idxSupport_iff t w i)
  have hErase : (support w).erase t0 = Finset.image t I := by
    ext x
    grind only
      [= Finset.subset_iff, = Finset.insert_eq_of_mem, = Finset.mem_image, = Finset.mem_erase,
        = Finset.mem_insert]
  have hcard_erase : ((support w).erase t0).card = I.card := by
    calc
      ((support w).erase t0).card = (Finset.image t I).card := by simp [hErase]
      _ = I.card := by simp [Finset.card_image_of_injective _ htinj]
  by_cases ht0w : t0 ∈ support w
  · have hcard : (support w).card = I.card + 1 := by
      simpa [hcard_erase] using (Finset.card_erase_add_one ht0w).symm
    have hOdd : Odd I.card := by
      have hE : Even (I.card + 1) := by simpa [hcard] using hEven
      exact Nat.not_even_iff_odd.1 (by simpa [Nat.even_add_one] using hE)
    exact ⟨fun _ => hOdd, fun _ => ht0w⟩
  · have hcard : (support w).card = I.card := by
      simpa [Finset.erase_eq_of_notMem ht0w] using hcard_erase
    have hnotOdd : ¬ Odd I.card :=
      Nat.not_odd_iff_even.2 (by simpa [hcard] using hEven)
    exact (iff_false_left ht0w).mpr hnotOdd

/-- Main spanning lemma: an even-weight word supported on `{t0} ∪ range t` is a `ZMod 2`-linear
combination of the star basis `t0 + t i`. -/
public theorem mem_span_evenBasisFamily_of_support_subset_of_even
    {t0 : Fin 24} {t : Fin 11 → Fin 24}
    (htinj : Function.Injective t) (hne : ∀ i, t0 ≠ t i)
    {w : BinWord 24}
    (hsupp : support w ⊆ insert t0 ((Finset.univ : Finset (Fin 11)).image t))
    (hEven : Even (weight w)) :
    w ∈ Submodule.span (ZMod 2) (Set.range (evenBasisFamily t0 t)) := by
  -- Let `I` be the set of indices whose coordinate is `1`.
  let I : Finset (Fin 11) := idxSupport t w
  have hI : ∀ i, i ∈ I ↔ t i ∈ support w := by
    intro i
    simpa [I] using (mem_idxSupport_iff t w i)
  -- Candidate decomposition.
  have hsum_mem :
      (∑ i ∈ I, evenBasisFamily t0 t i) ∈
        Submodule.span (ZMod 2) (Set.range (evenBasisFamily t0 t)) := by
    refine Submodule.sum_mem (Submodule.span (ZMod 2) (Set.range (evenBasisFamily t0 t))) ?_
    intro i hiI
    exact Submodule.subset_span ⟨i, rfl⟩
  have hEvenSupp : Even (support w).card := by
    simpa [GolayBounds.weight_eq_card_support] using hEven
  have ht0_parity :
      (t0 ∈ support w ↔ Odd I.card) :=
    by
      simpa [I] using
        (t0_mem_support_iff_odd_filter_card (t0 := t0) (t := t) htinj hne hsupp hEvenSupp)
  have hEq : (∑ i ∈ I, evenBasisFamily t0 t i) = w := by
    funext x
    by_cases hx0 : x = t0
    · subst x
      have hsum :
          (∑ i ∈ I, evenBasisFamily t0 t i) t0 = (I.card : ZMod 2) :=
        sum_evenBasisFamily_apply_t0 (t0 := t0) (t := t) I
      by_cases ht0w : t0 ∈ support w
      · have hcast : (I.card : ZMod 2) = 1 :=
          (ZMod.natCast_eq_one_iff_odd).2 ((ht0_parity).1 ht0w)
        have hw : w t0 = 1 := (GolayBounds.mem_support (w := w) t0).1 ht0w
        simp [hsum, hcast, hw]
      · have hcast : (I.card : ZMod 2) = 0 :=
          (ZMod.natCast_eq_zero_iff_even).2 (Nat.not_odd_iff_even.1 (by
            intro hOdd; exact ht0w ((ht0_parity).2 hOdd)))
        have hw : w t0 = 0 := (GolayBounds.not_mem_support (w := w) t0).1 ht0w
        simp [hsum, hcast, hw]
    · -- not `t0`
      by_cases hxImg : x ∈ ((Finset.univ : Finset (Fin 11)).image t)
      · rcases Finset.mem_image.1 hxImg with ⟨k, _hkU, rfl⟩
        by_cases hkI : k ∈ I
        · have hw : w (t k) = 1 := (GolayBounds.mem_support (w := w) (t k)).1 ((hI k).1 hkI)
          simp [sum_evenBasisFamily_apply_t (t0 := t0) (t := t) htinj hne I k, hkI, hw]
        · have hw : w (t k) = 0 := by
            have : t k ∉ support w := by
              simpa [hI k] using hkI
            exact (GolayBounds.not_mem_support (w := w) (t k)).1 this
          simp [sum_evenBasisFamily_apply_t (t0 := t0) (t := t) htinj hne I k, hkI, hw]
      · -- `x` is neither `t0` nor in the `t`-image: both sides vanish.
        have hx_not_supp : x ∉ support w := by
          intro hx
          have : x ∈ insert t0 ((Finset.univ : Finset (Fin 11)).image t) := hsupp hx
          rcases Finset.mem_insert.1 this with h | h
          · exact hx0 h
          · exact hxImg h
        have hx_ne_ti : ∀ i : Fin 11, x ≠ t i := by
          intro i h
          have : x ∈ ((Finset.univ : Finset (Fin 11)).image t) := by
            refine Finset.mem_image.2 ⟨i, by simp, h.symm⟩
          exact hxImg this
        have hx_sum : (∑ i ∈ I, evenBasisFamily t0 t i) x = 0 := by
          simp [Finset.sum_apply, evenBasisFamily_apply (t0 := t0) (t := t), hx0, hx_ne_ti]
        have hxw : w x = 0 := (GolayBounds.not_mem_support (w := w) x).1 hx_not_supp
        simp [hx_sum, hxw]
  -- conclude
  simpa [hEq] using hsum_mem
end

end GolayUniquenessSteps.WittDesignUniqueTheory.EvenBasisSpan

end SpherePacking.Dim24.Uniqueness.BS81.CodingTheory
