module
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.Discriminant
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.Cosets
public import SpherePacking.Dim24.Uniqueness.Rigidity.Classify.CenterInner
public import Mathlib.Topology.Instances.AddCircle.Real

/-!
# Discriminant pairing

We package the canonical pairing `L*/L × L*/L → ℝ/ℤ` induced by the real inner product on an
integral lattice.

Besides constructing this pairing on the discriminant group, we record that in the dimension-24
rigidity setup it vanishes on the subgroup generated by orbit cosets coming from center
differences (since the relevant inner products are integers).

## Main definitions
* `dualLatticePair`
* `discPair`

## Main statements
* `dualLatticePair_apply`
* `discPair_mk_mk`
-/

namespace SpherePacking.Dim24.Uniqueness.RigidityClassify

noncomputable section

open scoped RealInnerProductSpace Pointwise

local notation "ℝ²⁴" => EuclideanSpace ℝ (Fin 24)
local notation "𝕋" => AddCircle (1 : ℝ)

private lemma addCircle_int_cast_eq_zero (m : ℤ) : ((m : ℝ) : 𝕋) = 0 := by
  apply (AddCircle.coe_eq_zero_iff (p := (1 : ℝ)) (x := (m : ℝ))).2
  exact ⟨m, by simp⟩

/-- The raw pairing `L* × L* → ℝ/ℤ`. -/
@[expose] public noncomputable def dualLatticePair (L : Submodule ℤ ℝ²⁴) :
    DualLattice L →ₗ[ℤ] DualLattice L →ₗ[ℤ] 𝕋 :=
  by
    let toAddCircleHom : ℝ →+ 𝕋 :=
      QuotientAddGroup.mk' (AddSubgroup.zmultiples (1 : ℝ))
    refine LinearMap.mk₂ ℤ
      (fun x y => toAddCircleHom ⟪(x : ℝ²⁴), (y : ℝ²⁴)⟫) ?_ ?_ ?_ ?_
    · intro x₁ x₂ y
      simp [toAddCircleHom, inner_add_left]
    · intro n x y
      let f : ℝ²⁴ →+ ℝ :=
        { toFun := fun x => ⟪x, (y : ℝ²⁴)⟫
          map_zero' := by simp
          map_add' := by intro a b; simp [inner_add_left] }
      have hf :
          ⟪(n • (x : ℝ²⁴)), (y : ℝ²⁴)⟫ =
            n • ⟪(x : ℝ²⁴), (y : ℝ²⁴)⟫ := by
        simpa [f] using (f.map_zsmul (x : ℝ²⁴) n)
      simp [toAddCircleHom, hf]
    · intro x y₁ y₂
      simp [toAddCircleHom, inner_add_right]
    · intro n x y
      let f : ℝ²⁴ →+ ℝ :=
        { toFun := fun y => ⟪(x : ℝ²⁴), y⟫
          map_zero' := by simp
          map_add' := by intro a b; simp [inner_add_right] }
      have hf :
          ⟪(x : ℝ²⁴), (n • (y : ℝ²⁴))⟫ =
            n • ⟪(x : ℝ²⁴), (y : ℝ²⁴)⟫ := by
        simpa [f] using (f.map_zsmul (y : ℝ²⁴) n)
      simp [toAddCircleHom, hf]

/-- Unfolding lemma for `dualLatticePair` in terms of the real inner product. -/
@[simp]
public lemma dualLatticePair_apply (L : Submodule ℤ ℝ²⁴) (x y : DualLattice L) :
    dualLatticePair L x y = ((⟪(x : ℝ²⁴), (y : ℝ²⁴)⟫ : ℝ) : 𝕋) := by
  simp [dualLatticePair]

/- `dualLatticePair` vanishes on the embedded lattice, so it descends to the discriminant group. -/
/-! ### Pairing on the discriminant group -/

/-- The discriminant pairing `L*/L × L*/L → ℝ/ℤ`, bundled as a bilinear map. -/
@[expose] public noncomputable def discPair (L : Submodule ℤ ℝ²⁴) :
    DiscriminantGroup L →ₗ[ℤ] DiscriminantGroup L →ₗ[ℤ] 𝕋 := by
  -- Local helper: integers are `0` in `AddCircle (1 : ℝ)`.
  have addCircle_int_cast_eq_zero' (m : ℤ) : ((m : ℝ) : 𝕋) = 0 := by
    apply (AddCircle.coe_eq_zero_iff (p := (1 : ℝ)) (x := (m : ℝ))).2
    exact ⟨m, by simp⟩
  -- First, descend `dualLatticePair` in the right variable.
  have rightVanishes (x : DualLattice L) :
      latticeInDual L ≤ LinearMap.ker (dualLatticePair L x) := by
    intro y hy
    have hyL : ((y : DualLattice L) : ℝ²⁴) ∈ L := (mem_latticeInDual_iff (L := L) y).1 hy
    have hxInt : ⟪(x : ℝ²⁴), ((y : DualLattice L) : ℝ²⁴)⟫ ∈ (1 : Submodule ℤ ℝ) := by
      simpa [DualLattice] using x.property _ hyL
    rcases (Submodule.mem_one.mp hxInt) with ⟨m, hm⟩
    have hxy : ⟪(x : ℝ²⁴), (y : ℝ²⁴)⟫ = (m : ℝ) := by
      simpa using hm.symm
    simp_all
  let discPairRight (x : DualLattice L) : DiscriminantGroup L →ₗ[ℤ] 𝕋 :=
    Submodule.liftQ (p := latticeInDual L) (dualLatticePair L x) (rightVanishes x)
  have discPairRight_mk (x y : DualLattice L) :
      discPairRight x (Submodule.Quotient.mk y) = dualLatticePair L x y := by
    rfl
  let liftRight : DualLattice L →ₗ[ℤ] DiscriminantGroup L →ₗ[ℤ] 𝕋 :=
    { toFun := fun x => discPairRight x
      map_add' := by
        intro x₁ x₂
        apply LinearMap.ext
        intro q
        refine Quotient.inductionOn q ?_
        intro y
        change
          discPairRight (x₁ + x₂) (Submodule.Quotient.mk y) =
            discPairRight x₁ (Submodule.Quotient.mk y) +
              discPairRight x₂ (Submodule.Quotient.mk y)
        have h :=
          congrArg (fun f : DualLattice L →ₗ[ℤ] 𝕋 => f y) ((dualLatticePair L).map_add x₁ x₂)
        simp [discPairRight_mk]
      map_smul' := by
        intro n x
        apply LinearMap.ext
        intro q
        refine Quotient.inductionOn q ?_
        intro y
        change
          discPairRight (n • x) (Submodule.Quotient.mk y) =
            n • discPairRight x (Submodule.Quotient.mk y)
        have h :=
          congrArg (fun f : DualLattice L →ₗ[ℤ] 𝕋 => f y) (map_zsmul (dualLatticePair L) n x)
        simp [discPairRight_mk] }
  -- Now descend in the left variable.
  refine Submodule.liftQ (p := latticeInDual L) liftRight ?_
  intro x hx
  change liftRight x = 0
  apply LinearMap.ext
  intro q
  refine Quotient.inductionOn q ?_
  intro y
  have hxL : ((x : DualLattice L) : ℝ²⁴) ∈ L := (mem_latticeInDual_iff (L := L) x).1 hx
  have hyInt : ⟪(y : ℝ²⁴), ((x : DualLattice L) : ℝ²⁴)⟫ ∈ (1 : Submodule ℤ ℝ) := by
    simpa [DualLattice] using y.property _ hxL
  rcases (Submodule.mem_one.mp hyInt) with ⟨m, hm⟩
  have hmyx : ⟪(y : ℝ²⁴), (x : ℝ²⁴)⟫ = (m : ℝ) := by
    simpa using hm.symm
  have hxy : ⟪(x : ℝ²⁴), (y : ℝ²⁴)⟫ = (m : ℝ) := by
    simpa [real_inner_comm] using hmyx
  have hm0 : ((m : ℝ) : 𝕋) = 0 := addCircle_int_cast_eq_zero' (m := m)
  have hx0 : dualLatticePair L x y = 0 := by
    simp [dualLatticePair_apply, hxy, hm0]
  change discPairRight x (Submodule.Quotient.mk y) = 0
  simp [discPairRight_mk, hx0]

/-- Computing `discPair` on representatives in the dual lattice. -/
@[simp]
public lemma discPair_mk_mk (L : Submodule ℤ ℝ²⁴) (x y : DualLattice L) :
    discPair (L := L) (Submodule.Quotient.mk x) (Submodule.Quotient.mk y) =
      dualLatticePair L x y := by
  -- Expand `discPair` and use the `liftQ` computation rule twice.
  rfl

private theorem orbitCoset_pair_eq_zero (S : PeriodicSpherePacking 24)
    (hSpec : HasLeechDistanceSpectrum S) (hDens : S.density = LeechPacking.density)
    (x0 : S.centers) (q1 q2 : Quotient S.addAction.orbitRel) :
    discPair (L := S.lattice)
        (Submodule.Quotient.mk (centerDiffDual (S := S) hSpec hDens x0 (Quotient.out q2)))
        (orbitCoset (S := S) hSpec hDens x0 q1)
      = 0 := by
  -- Reduce to representatives in `S.centers`.
  refine Quotient.inductionOn q1 ?_
  intro x
  -- Unfold the coset and use the integrality of center-difference inner products.
  -- `orbitCoset ⟦x⟧ = centerCoset x = mk (x - x0)`.
  have hx :
      orbitCoset (S := S) hSpec hDens x0 (Quotient.mk'' x) =
        Submodule.Quotient.mk (centerDiffDual (S := S) hSpec hDens x0 x) := by
    simp [orbitCoset, centerCoset]
  -- The value is an integer, hence `0` in `AddCircle (1 : ℝ)`.
  rcases (HasLeechDistanceSpectrum.inner_centerDiff_eq_int (S := S) hSpec x0 x (Quotient.out q2))
      with ⟨m, hm⟩
  have hzero :
      dualLatticePair S.lattice
          (centerDiffDual (S := S) hSpec hDens x0 (Quotient.out q2))
          (centerDiffDual (S := S) hSpec hDens x0 x) =
        0 := by
    have hinner :
        ⟪(centerDiffDual (S := S) hSpec hDens x0 (Quotient.out q2) : ℝ²⁴),
              (centerDiffDual (S := S) hSpec hDens x0 x : ℝ²⁴)⟫
            = (m : ℝ) := by
      simpa [centerDiffDual, real_inner_comm] using hm
    have hm0 : ((m : ℝ) : 𝕋) = 0 := addCircle_int_cast_eq_zero (m := m)
    simp [dualLatticePair_apply, hinner, hm0]
  simp [hx, discPair_mk_mk, hzero]

end

end SpherePacking.Dim24.Uniqueness.RigidityClassify
