module
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayDefs
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.LinearCode
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.CodeFromOctads.Span
import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.CodeFromOctads.Determine
import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.Weight8Count
import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.WittDesignUniqueTheory.DesignUniqueness

/-!
# Uniqueness of the extended binary Golay code

This file proves the main coding-theory input for BS81 Lemma 21: if `C₁ C₂ : Code 24` are both
extended binary Golay codes, then they are equivalent under a permutation of coordinates.
-/

namespace SpherePacking.Dim24.Uniqueness.BS81.CodingTheory
noncomputable section

/-!
## Step 1: weight-8 words count

From the `[24,12,8]` invariants (linearity, `|C|=2^12`, min distance `8`) one can derive the full
weight enumerator and in particular the exact number of weight-8 codewords: `759`.
-/

/-!
## Step 2: Witt design `S(5,8,24)` from the weight-8 words, and uniqueness
-/

/--
From an extended binary Golay code, obtain the associated Steiner system `S(5,8,24)` of octads.
-/
public theorem steiner_S_5_8_24_from_isExtendedBinaryGolayCode
    (C : Code 24) (hC : IsExtendedBinaryGolayCode C) :
    ∃ S : SteinerSystem 24 8 5, S.blocks = octadsFromCode C := by
  refine WittDesign.steiner_S_5_8_24_of_weight8_count (C := C) hC.minDist_ge ?_
  simpa using
    (GolayUniquenessSteps.weight8Words_card_eq_759_of_isExtendedBinaryGolayCode_step (C := C) hC)

/-!
## Step 3: the code is determined (up to equivalence) by its octads

Standard claim: a binary code with the Golay parameters is generated by its weight-8 words, and
those are exactly the octads of the Witt design.
-/

namespace GolayUniquenessSteps

/--
If two codes are Golay codes, then their octads define isomorphic Steiner systems, hence are related
by some coordinate permutation.
-/
public theorem exists_perm24_of_isomorphic_octads_step
    (C₁ C₂ : Code 24)
    (h₁ : IsExtendedBinaryGolayCode C₁)
    (h₂ : IsExtendedBinaryGolayCode C₂) :
    ∃ σ : Equiv (Fin 24) (Fin 24),
      octadsFromCode C₁ = {B | (Finset.map σ.toEmbedding B) ∈ octadsFromCode C₂} := by
  have hN (C : Code 24) (hC : IsExtendedBinaryGolayCode C) : Set.ncard (weight8Words C) = 759 := by
    simpa using (weight8Words_card_eq_759_of_isExtendedBinaryGolayCode_step (C := C) hC)
  rcases
      WittDesign.steiner_S_5_8_24_of_weight8_count (C := C₁) h₁.minDist_ge (hN C₁ h₁) with
    ⟨S₁, hS₁⟩
  rcases
      WittDesign.steiner_S_5_8_24_of_weight8_count (C := C₂) h₂.minDist_ge (hN C₂ h₂) with
    ⟨S₂, hS₂⟩
  rcases WittDesignUniqueTheory.steiner_S_5_8_24_unique_classical (S₁ := S₁) (S₂ := S₂) with
    ⟨σ, hσ⟩
  refine ⟨σ, ?_⟩
  have : S₁.blocks = {B | (Finset.map σ.toEmbedding B) ∈ S₂.blocks} := by simpa using hσ
  simpa [hS₁, hS₂] using this

/--
If octad sets correspond under `σ` and both codes are generated by their octads, then the codes
agree after permuting coordinates.
-/
public theorem permuteCode_eq_of_octads_eq_step
    (C₁ C₂ : Code 24)
    (h₁ : IsExtendedBinaryGolayCode C₁)
    (h₂ : IsExtendedBinaryGolayCode C₂)
    (σ : Equiv (Fin 24) (Fin 24))
    (hoct : octadsFromCode C₁ = {B | (Finset.map σ.toEmbedding B) ∈ octadsFromCode C₂})
    (hgen₁ :
      LinearCode.submodule (n := 24) C₁ h₁.linear =
        GolayUniquenessSteps.CodeFromOctads.octadSubmodule C₁)
    (hgen₂ :
      LinearCode.submodule (n := 24) C₂ h₂.linear =
        GolayUniquenessSteps.CodeFromOctads.octadSubmodule C₂) :
    permuteCode (n := 24) σ.symm C₁ = C₂ := by
  simpa using
    GolayUniquenessSteps.CodeFromOctads.permuteCode_eq_of_octads_eq_of_generated_by_octads
      C₁ C₂ h₁.linear h₂.linear σ hoct hgen₁ hgen₂

end GolayUniquenessSteps

/--
Uniqueness of extended binary Golay codes up to coordinate permutation, assuming generation by
octads for each code.
-/
public theorem extendedBinaryGolay_unique
    (C₁ C₂ : Code 24)
    (h₁ : IsExtendedBinaryGolayCode C₁)
    (h₂ : IsExtendedBinaryGolayCode C₂)
    (hgen₁ :
      LinearCode.submodule (n := 24) C₁ h₁.linear =
        GolayUniquenessSteps.CodeFromOctads.octadSubmodule C₁)
    (hgen₂ :
      LinearCode.submodule (n := 24) C₂ h₂.linear =
        GolayUniquenessSteps.CodeFromOctads.octadSubmodule C₂) :
    ∃ σ : Equiv (Fin 24) (Fin 24), permuteCode (n := 24) σ C₁ = C₂ := by
  rcases
      GolayUniquenessSteps.exists_perm24_of_isomorphic_octads_step (C₁ := C₁) (C₂ := C₂)
        h₁ h₂ with
    ⟨σ, hoct⟩
  refine ⟨σ.symm, ?_⟩
  exact GolayUniquenessSteps.permuteCode_eq_of_octads_eq_step C₁ C₂ h₁ h₂ σ hoct hgen₁ hgen₂

end

end SpherePacking.Dim24.Uniqueness.BS81.CodingTheory
