module
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.Uniqueness
public import
SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.WittDesignUniqueTheory.ClassicalWitt.SharpInput
public import Mathlib.Data.Set.Card
public import SpherePacking.Dim24.Uniqueness.BS81.CodingTheory.GolayUniqueness.CodeFromOctads.Span

/-!
# Golay code is generated by octads

For an extended binary Golay code `C`, the `ZMod 2`-submodule `LinearCode.submodule C` is
generated by the weight-`8` codewords (the octads).

This supplies an interface lemma used by the uniqueness development
`CodingTheory/GolayUniqueness/Main.lean`.

## Main statement
* `GolayOctadGeneration.codeSubmodule_eq_octadSubmodule_of_isExtendedBinaryGolayCode`
-/

namespace SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.IsometrySteps

noncomputable section

open Set
open Uniqueness.BS81.CodingTheory

namespace GolayOctadGeneration

open GolayUniquenessSteps

open LinearCode

local notation "Word" => BinWord 24

private lemma submodule_eq_of_le_of_ncard_eq
    (S T : Submodule (ZMod 2) Word)
    (hST : S ≤ T)
    (hcard : Set.ncard (S : Set Word) = Set.ncard (T : Set Word)) :
    S = T := by
  have hEq : (S : Set Word) = (T : Set Word) :=
    Set.eq_of_subset_of_ncard_le (s := (S : Set Word)) (t := (T : Set Word)) hST
      (le_of_eq hcard.symm)
  simp_all

private lemma octadSubmodule_eq_codeSubmodule_of_ncard_eq
    (C : Code 24) (hC : IsLinearCode C)
    (hcard :
      Set.ncard (GolayUniquenessSteps.CodeFromOctads.octadSubmodule C : Set Word) = Set.ncard C) :
    GolayUniquenessSteps.CodeFromOctads.octadSubmodule C =
      LinearCode.submodule (n := 24) C hC := by
  have hle :
      GolayUniquenessSteps.CodeFromOctads.octadSubmodule C ≤ LinearCode.submodule (n := 24) C hC :=
    GolayUniquenessSteps.CodeFromOctads.octadSubmodule_le_codeSubmodule (C := C) hC
  refine
    submodule_eq_of_le_of_ncard_eq (S := GolayUniquenessSteps.CodeFromOctads.octadSubmodule C)
      (T := LinearCode.submodule (n := 24) C hC) hle ?_
  -- `submodule C` has the same underlying set as `C`.
  assumption

private lemma octadSubmodule_ncard_eq_two_pow_12_of_exists_witt
    (C : Code 24)
    (S : SteinerSystem 24 8 5)
    (hS : S.blocks = octadsFromCode C) :
    Set.ncard (GolayUniquenessSteps.CodeFromOctads.octadSubmodule C : Set (BinWord 24)) =
      2 ^ 12 := by
  -- `designCode S` is definitionaly `octadSubmodule C` once `S.blocks = octadsFromCode C`.
  have hcard :
      Set.ncard (GolayUniquenessSteps.WittDesignUniqueTheory.ClassicalWitt.designCode S) = 2 ^ 12 :=
    GolayUniquenessSteps.WittDesignUniqueTheory.ClassicalWitt.designCode_card_eq (S := S)
  simpa [GolayUniquenessSteps.WittDesignUniqueTheory.ClassicalWitt.designCode,
    GolayUniquenessSteps.WittDesignUniqueTheory.ClassicalWitt.codeFromSteinerSystem,
    GolayUniquenessSteps.WittDesignUniqueTheory.ClassicalWitt.codeFromBlocks,
    GolayUniquenessSteps.WittDesignUniqueTheory.ClassicalWitt.blockSubmodule,
    GolayUniquenessSteps.WittDesignUniqueTheory.ClassicalWitt.blockWordSet,
    GolayUniquenessSteps.CodeFromOctads.octadSubmodule,
    GolayUniquenessSteps.CodeFromOctads.octadWordSet,
    hS] using hcard

/-- An extended binary Golay code is generated by its octads (as a `ZMod 2`-submodule). -/
public theorem codeSubmodule_eq_octadSubmodule_of_isExtendedBinaryGolayCode
    (C : Code 24) (hC : IsExtendedBinaryGolayCode C) :
    LinearCode.submodule (n := 24) C hC.linear =
      GolayUniquenessSteps.CodeFromOctads.octadSubmodule C := by
  -- Build the Witt design from the weight-8 words.
  rcases
      (Uniqueness.BS81.CodingTheory.steiner_S_5_8_24_from_isExtendedBinaryGolayCode
        (C := C) hC) with ⟨S, hS⟩
  have hOctadCard :
      Set.ncard (GolayUniquenessSteps.CodeFromOctads.octadSubmodule C : Set (BinWord 24)) =
        Set.ncard C := by
    simpa [hC.card_eq] using octadSubmodule_ncard_eq_two_pow_12_of_exists_witt (C := C) (S := S) hS
  simpa using
    (octadSubmodule_eq_codeSubmodule_of_ncard_eq (C := C) hC.linear hOctadCard).symm

end GolayOctadGeneration

end

end SpherePacking.Dim24.Uniqueness.BS81.Thm15.Lemma21.IsometrySteps
